server:
  port: 8081

spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
    username: postgres.tfglbsxvqtshorsvxrto
    password: petoneDB2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true